export CEOBE__DB__HOST="127.0.0.1"
export CEOBE__DB__USER="root"
export CEOBE__DB__PASSWORD="123"

export CEOBE__REDIS__PASSWORD="123"

export CEOBE__WARNING_TIMEOUT=150
export CEOBE__REMOVE_TIMEOUT=300
